const EXACT_MATCH = 'EXACT_MATCH';
const PARTIAL_MATCH = 'PARTIAL_MATCH';
const STARTS_WITH = 'STARTS_WITH';

const ASCENDING = 'ASCENDING';
const DESCENDING = 'DESCENDING';

const MATCH = {
  '**': EXACT_MATCH,
  '--': PARTIAL_MATCH,
  '*-': STARTS_WITH
};

export {
  EXACT_MATCH,
  PARTIAL_MATCH,
  STARTS_WITH,
  ASCENDING,
  DESCENDING,
  MATCH
};
