const EXACT_MATCH = 'EXACT_MATCH';
const PARTIAL_MATCH = 'PARTIAL_MATCH';
const STARTS_WITH = 'STARTS_WITH';
const ASCENDING = 'ASCENDING';
const DESCENDING = 'DESCENDING';
const EXACT_SEARCH_DISPLAY = '**';
const PARTIAL_SEARCH_DISPLAY = '*-';
const STARTS_WITH_SEARCH_DISPLAY = '--';

export {
  EXACT_MATCH,
  PARTIAL_MATCH,
  STARTS_WITH,
  ASCENDING,
  DESCENDING,
  EXACT_SEARCH_DISPLAY,
  PARTIAL_SEARCH_DISPLAY,
  STARTS_WITH_SEARCH_DISPLAY
};
